name: Build RTL8188Eu Driver

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Extract kernel headers
      run: |
        mkdir -p kernel_headers
        tar -xzvf linux-headers.tar.gz -C kernel_headers

    - name: Compile driver
      run: |
        cd rtl8188eu
        make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- KSRC=../kernel_headers

    - name: Upload driver artifact
      # 关键修正：升级到 upload-artifact@v4 并修复路径
      uses: actions/upload-artifact@v4
      with:
        name: rtl8188eu-driver
        path: rtl8188eu/8188eu.ko  # 注意驱动文件名可能为 8188eu.ko 而非 rtl8188eu.ko
